### ISSUE TITLE
stuck on Downloading Metadata...

### ISSUE THREAD

**Issue by gunysa1** [r12habh/Google-Colab-Torrent-Downloader-To-Drive#25] opened 2021-03-30 13:01 UTC
stuck on Downloading Metadata...

**Comment by r12habh** [comment] 2021-04-05 06:43
use magnet links

**Comment by ethanaobrien** [comment] 2021-04-12 17:04
@gunysa1 also see #20 

@r12habh please close this. It is a duplicate of #20

**Closed** 2021-04-12 17:08 UTC
